"""
Investigation Tasks Routes

Manages AI-generated field investigation tasks.
Tasks are created when the AI identifies missing evidence that
requires real-world validation (PRD Section 4.2: Human-in-the-Loop Field Tasks).

Task statuses: pending, scheduled, completed, skipped (SAD Section 11).
"""
# This file defines the API endpoints for managing investigation tasks generated by the
#  AI.
# The main functionalities include:
# - Listing all investigation tasks for a specific business case, along with their
#  status.
# - Updating the status of a task (e.g., marking it as completed with findings).
# - Marking a task as completed and submitting the findings for AI re-analysis, which
#  may lead to updated recommendations based on the new evidence.
# - Allowing users to skip a task if they choose not to complete it, which will impact
#  the AI's confidence in its recommendations.
# The endpoints in this file will interact with the database to manage task records,
# update their status, and trigger the necessary AI processes when tasks are completed
#  or skipped. This allows for a dynamic investigation process where the AI can adapt its
# recommendations based on the real-world evidence collected by the user through these
# tasks.

# For example, when the AI identifies a task that requires a site visit to validate a specific fact, the user can view this task in the list of tasks for their case. Once they complete the task and submit their findings, the POST /api/cases/{case_id}/tasks/{task_id}/complete endpoint will be called, which will update the task status to completed and trigger a re-analysis of the business case with the new evidence. If the user decides to skip the task, the POST /api/cases/{case_id}/tasks/{task_id}/skip endpoint will be called, which will update the task status to skipped and adjust the AI's confidence in its recommendations accordingly. This iterative process allows users to gather real-world evidence and see how it impacts the AI's analysis and recommendations for their F&B business case.
from fastapi import APIRouter, Depends

from app.db.session import get_db

router = APIRouter()


@router.get("/{case_id}/tasks")
async def list_tasks(case_id: str, db=Depends(get_db)):
    """List all investigation tasks for a business case."""
    # TODO: Return tasks with status
    pass


@router.put("/{task_id}")
async def update_task(task_id: str, db=Depends(get_db)):
    """Update task status (e.g., mark as completed with findings)."""
    # TODO: Update status, store findings, trigger re-analysis if completed
    pass


@router.post("/{task_id}/complete")
async def complete_task(task_id: str, db=Depends(get_db)):
    """Mark a task as completed and submit findings for AI re-analysis."""
    # TODO: Store findings, trigger AI re-analysis (PRD Section 4.2: Re-analysis)
    pass


@router.post("/{task_id}/skip")
async def skip_task(task_id: str, db=Depends(get_db)):
    """Skip a task (user chooses not to complete it)."""
    # TODO: Mark as skipped, note impact on recommendation confidence
    pass
